scripts:
  # "Pre" scripts run after your custom repos have been imported.
  pre:
    - flatpaks.sh
    - image-info.sh
    - repositories.sh
  # "Post" scripts run at the end of the build process.
  post:
    - fonts.sh
    - hosts.sh
    - repositories.sh
# Custom RPM configuration.
rpm:
  # These RPMs will be installed from your enabled repositories.
  install:
    - adobe-source-code-pro-fonts
    - android-tools
    - bat
    - btop
    - cascadiacode-nerd-fonts
    - chatgpt-shell-cli
    - devpod
    - duperemove
    - eza
    - fd-find
    - gamescope
    - glow
    - google-droid-sans-mono-fonts
    - google-go-mono-fonts
    - guestfs-tools
    - ibm-plex-mono-fonts
    - jetbrains-mono-fonts-all
    - libgcc
    - libgda
    - libgda-sqlite
    - libvirt-daemon-config-network
    - libvirt-daemon-kvm
    - micro
    - mozilla-fira-mono-fonts
    - p7zip
    - p7zip-plugins
    - powerline-fonts
    - proton-vpn-gnome-desktop
    - python3-libguestfs
    - qemu-kvm
    - starship
    - telnet
    - ubuntu-nerd-fonts
    - ubuntumono-nerd-fonts
    - util-linux-user
    - ventoy
    - virt-install
    - virt-manager
    - virt-top
    - virt-viewer
    - xbindkeys
    - zenity
    - zsh
  # These RPMs will be removed from the system image.
  remove:
kinoite:
  scripts:
    pre:
    post:
  rpm:
    install:
      - kommit
      - latte-dock-nightly
    remove:
silverblue:
  scripts:
    pre:
    post:
      - gnome-ext.sh
  rpm:
    install:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-drive-menu
    remove:
