main:
  scripts:
    # "Pre" scripts run after your custom repos have been imported.
    pre:
      - charm.sh
      - flatpaks.sh
      - image-info.sh
      - terra.sh
    # "Post" scripts run at the end of the build process.
    post:
      - devpod.sh
      - fonts.sh
      - gnome-ext.sh
      - hosts.sh
  # Custom RPM configuration.
  rpm:
    # A list of urls of ".repo" files that should be added to your system.
    # Tip: Use `%FEDORA_VERSION%` instead of static Fedora version numbers.
    repos:
      - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%FEDORA_VERSION%/kylegospo-bazzite-fedora-%FEDORA_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/chatGPT-shell-cli/repo/fedora-%FEDORA_VERSION%/kylegospo-chatGPT-shell-cli-fedora-%FEDORA_VERSION%.repo
    # These RPMs will be installed from your enabled repositories.
    install:
      - adobe-source-code-pro-fonts
      - android-tools
      - bat
      - btop
      - cascadiacode-nerd-fonts
      - chatgpt-shell-cli
      - duperemove
      - exa
      - fd-find
      - gamescope
      - glow
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-drive-menu
      - google-droid-sans-mono-fonts
      - google-go-mono-fonts
      - guestfs-tools
      - ibm-plex-mono-fonts
      - jetbrains-mono-fonts-all
      - libgcc
      - libgda
      - libgda-sqlite
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - micro
      - mozilla-fira-mono-fonts
      - p7zip
      - p7zip-plugins
      - powerline-fonts
      - python3-libguestfs
      - qemu-kvm
      - telnet
      - ubuntu-nerd-fonts
      - ubuntumono-nerd-fonts
      - util-linux-user
      - virt-install
      - virt-manager
      - virt-top
      - virt-viewer
      - xbindkeys
      - zenity
      - zsh
    # These RPMs will be removed from the system image.
    remove:
